services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/rails/
    environment:
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOSTNAME: "${DATABASE_HOSTNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"